"""empty message

Revision ID: a59bed9f0238
Revises: 3945e1a213fc
Create Date: 2024-02-20 17:24:23.132167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59bed9f0238'
down_revision = '3945e1a213fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('altura')
        batch_op.drop_column('genero')
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
